### ISSUE TITLE
New release checklist

### ISSUE THREAD

**Issue by benhylau** [tomeshnet/ipfs-live-streaming#104]
Prepare new release that reflects changes from streaming Our Networks 2019. Here is a checklist:

- [ ] Update text and diagrams on [README](https://github.com/tomeshnet/ipfs-live-streaming/blob/master/README.md) to reflect revised architecture and installation
- [ ] Market the new live archive and hash-bookmark feature (do we port the share bar?)
- [ ] Port back relevant player changes from [Our Networks player](https://ournetworks.ca/livestream/)
- [ ] Make sure https://github.com/ournetworks/ournetworks.ca/issues/157 does not require changes to this repo (I don't expect any, unless we also make a share bar here)
- [ ] Merge https://github.com/tomeshnet/ipfs-live-streaming/pull/103 and add documentation for use
- [ ] Decide what to do with [live.mesh.world](https://live.mesh.world/) and its relation to this repo (is it an official hosted service / demo)?
- [ ] Tag new release

**Comment by benhylau** [comment]
@darkdrgn2k is there anything I missed?

**Comment by benhylau** [comment]
>(do we port the share bar?)

So I "ported" the share bar, and also added support for VOD bookmarking. Just need to update README to reflect that.

I propose we do the following in this order:

1. Merge #103 and verify it by redeploying to live.mesh.world
2. Update README to reflect all the updates (bookmarks, debian deploy script #103, new diagrams to reflect the combined rtmp+ipfs-origin)
3. Tag release

@darkdrgn2k do we need something to deal with the date rotation of the live manifest?
